all:
  children:
    rpis:
      hosts:
        rPI1:
          ansible_host: 192.168.81.149
        rPI2:
          ansible_host: 192.168.81.150
  vars:
    # Typical values:
    # - Fedora Server flashed via arm-image-installer --addkey: root
    # - Raspberry Pi OS: pi
    ansible_user: razvan
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
