adapter = "hci0"
local_name = "WoS1MB"
company_id = 0x0969
manufacturer_mac_label = ""
service_uuids = [
  "CBA20D00-224D-11E6-9FB8-0002A5D5C51B",
  "B000"
]
fd3d_service_data_hex = "00"
include_tx_power = true
fw_major = 1
fw_minor = 0
